//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKiDatPhong
    {
        public int ID_DangKi { get; set; }
        public string Email { get; set; }
        public string HoTen { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> ID_Phong { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public string Message { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
