//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public int IDGiaoDich { get; set; }
        public Nullable<int> IDDatPhong { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }
        public Nullable<int> IDDichVu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> BuyTime { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
