//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachSan()
        {
            this.Phongs = new HashSet<Phong>();
        }
    
        public int IDKhachSan { get; set; }
        public Nullable<int> IDTinhThanh { get; set; }
        public Nullable<int> IDHinhAnh { get; set; }
        public string MaKhachSan { get; set; }
        public string TenKhachSan { get; set; }
        public string DiaChi { get; set; }
        public string GioiThieu { get; set; }
        public string TieuDe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> Star { get; set; }
    
        public virtual HinhAnh HinhAnh { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
