//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.DangKiDatPhongs = new HashSet<DangKiDatPhong>();
            this.DatPhongs = new HashSet<DatPhong>();
            this.Phong_HinhAnh = new HashSet<Phong_HinhAnh>();
        }
    
        public int IDPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> ID_ViTri { get; set; }
        public string TrangThai { get; set; }
        public Nullable<long> GiaPhong { get; set; }
        public Nullable<int> ID_LoaiPhong { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> IDKhachSan { get; set; }
        public Nullable<int> GiaKM { get; set; }
        public Nullable<int> Star { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKiDatPhong> DangKiDatPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        public virtual KhachSan KhachSan { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong_HinhAnh> Phong_HinhAnh { get; set; }
        public virtual ViTri ViTri { get; set; }
    }
}
